### ISSUE TITLE
Steam API Support for friends list and P2P

### ISSUE THREAD

**Issue by LillyWho** [Patrick-van-Halm/dv-multiplayer-mod#13] opened 2021-01-31 12:06 UTC
For this one I don't have an idea for an implementation concept, but it would be essentially the perfect feature as it does away with port forwarding and the need to know your public IP.

You could just join your friend via the friends list and Steam does the rest. Where and how you'd get access to the API, I can't unfortunately say.

**Comment by Patrick-van-Halm** [comment] 2021-01-31 12:59
Steam uses Steamworks for this so this is the same as that enhancement: #10

**Comment by LillyWho** [comment] 2021-02-03 13:02
We derped.

**Comment by Patrick-van-Halm** [comment] 2021-02-03 17:31
Yes we did but its all good

**Comment by ChrisR1701** [comment] 2021-02-19 12:25
@Patrick-van-Halm This can probably be closed as it is a duplicate of #10 as mentioned above 🙂

**Closed as completed** 2021-02-19 14:47 UTC
Labels: duplicate, enhancement
